require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
platform :ios, '11.0'

target 'MobileAgentReactNative' do
  use_unimodules!
  config = use_native_modules!
  use_frameworks!

  dynamic_frameworks = [] # <- swift libraries names

  # Make all the other frameworks into static frameworks by overriding the static_framework? function to return true
  # https://stackoverflow.com/a/60914505/10552895
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if !dynamic_frameworks.include?(pod.name)
        puts "Overriding the static_framework? method for #{pod.name}"
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end



  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'MobileAgentReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    react_native_post_install(installer)
  end


  permissions_path = '../node_modules/react-native-permissions/ios'

#  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
#  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
#  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
#  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
#  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
#  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
   pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
#  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
#  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
#  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
#  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
#  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
#  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
#  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
#  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
#  pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
#  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
#  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"

end
